name: VoxType
options:
  bundleIdPrefix: com.voxtype
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"

targets:
  VoxType:
    type: application
    platform: macOS
    sources:
      - path: VoxType
        excludes:
          - "*.xcassets"
          - Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.voxtype.app
        INFOPLIST_FILE: VoxType/Info.plist
        CODE_SIGN_ENTITLEMENTS: VoxType/VoxType.entitlements
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_HARDENED_RUNTIME: YES
        # Menu bar app settings
        LSUIElement: YES
    info:
      path: VoxType/Info.plist
      properties:
        CFBundleDisplayName: VoxType
        CFBundleName: VoxType
        NSMicrophoneUsageDescription: VoxType needs microphone access for voice-to-text transcription.
        NSAccessibilityUsageDescription: VoxType needs accessibility access to monitor global hotkeys for voice recording.
        LSUIElement: true
        CFBundleURLTypes:
          - CFBundleURLName: com.voxtype.app
            CFBundleURLSchemes:
              - voxtype
    entitlements:
      path: VoxType/VoxType.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.device.audio-input: true
        com.apple.security.network.client: true
