"""add_github_username_to_whitelist

Revision ID: 25d9d52ace8d
Revises: 7e34a55698f8
Create Date: 2026-02-03 16:49:43.921055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d9d52ace8d'
down_revision: Union[str, Sequence[str], None] = '7e34a55698f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whitelist', sa.Column('github_username', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whitelist', 'github_username')
    # ### end Alembic commands ###
